#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL
# Run DRBL conf and functions

# Setting
# Source function library.
[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

# Source DRBL setting
if [ ! -f "/etc/drbl/drbl.conf" ]; then
  echo "File /etc/drbl/drbl.conf not found! Program terminated!" 
  exit 1
fi
. /etc/drbl/drbl.conf

# check if drbl-functions exists
if [ ! -f "$DRBL_SCRIPT_PATH/sbin/drbl-functions" ]; then
  echo "File $DRBL_SCRIPT_PATH/sbin/drbl-functions not found! Program terminated!" 
  exit 1
fi
. $DRBL_SCRIPT_PATH/sbin/drbl-functions
