#!/bin/bash
# Steven Shiau <steven@nchc.org.tw>
# License: GPL
# Description: To clean the dhcpd.leases then restart dhcpd

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions

#
check_if_root

# find the path of dhcpd.leases ($DHCPDLEASE_DIR), such as /var/lib/dhcp3 in debian or /var/lib/dhcp in FC1-4.
get_dhcpdlease_dir

# drcp_srv_name is loaded from conf/drbl.conf
if is_systemd_init; then
  /bin/systemctl stop $DHCP_SRV_NAME.service || /etc/init.d/$DHCP_SRV_NAME stop
fi
[ -f "$DHCPDLEASE_DIR/dhcpd.leases" ] && rm -f $DHCPDLEASE_DIR/dhcpd.leases
[ -f "$DHCPDLEASE_DIR/dhcpd.leases~" ] && rm -f $DHCPDLEASE_DIR/dhcpd.leases~
touch $DHCPDLEASE_DIR/dhcpd.leases
if is_systemd_init; then
  /bin/systemctl start $DHCP_SRV_NAME.service || /etc/init.d/$DHCP_SRV_NAME start
else
  service $DHCP_SRV_NAME restart
fi
